import { PDFDocument, StandardFonts, rgb } from "pdf-lib";

type InvoiceItem = {
  medicine_name: string;
  batch_number: string;
  quantity: number;
  unit_price: number;
  line_total: number;
};

type InvoicePayload = {
  storeName: string;
  storeAddress?: string | null;
  storeContact?: string | null;
  invoiceNumber: string;
  saleDate: string;
  customerName?: string | null;
  paymentMethod: string;
  subtotal: number;
  discountAmount: number;
  taxAmount: number;
  totalAmount: number;
  dueAmount: number;
  notes?: string | null;
  currencyCode: string;
  items: InvoiceItem[];
};

export async function buildInvoicePdf(payload: InvoicePayload) {
  const pdf = await PDFDocument.create();
  const page = pdf.addPage([595, 842]);
  const regular = await pdf.embedFont(StandardFonts.Helvetica);
  const bold = await pdf.embedFont(StandardFonts.HelveticaBold);
  const { height } = page.getSize();

  const drawText = (text: string, x: number, y: number, size = 10, useBold = false, color = rgb(0.15, 0.17, 0.23)) => {
    page.drawText(text, {
      x,
      y,
      size,
      font: useBold ? bold : regular,
      color
    });
  };

  page.drawRectangle({
    x: 36,
    y: height - 120,
    width: 523,
    height: 84,
    color: rgb(0.08, 0.21, 0.16)
  });

  drawText(payload.storeName, 52, height - 72, 22, true, rgb(1, 1, 1));
  if (payload.storeAddress) {
    drawText(payload.storeAddress, 52, height - 92, 10, false, rgb(0.92, 0.95, 0.98));
  }
  if (payload.storeContact) {
    drawText(payload.storeContact, 52, height - 106, 10, false, rgb(0.92, 0.95, 0.98));
  }

  drawText("Invoice", 420, height - 72, 18, true, rgb(1, 1, 1));
  drawText(payload.invoiceNumber, 420, height - 92, 10, false, rgb(0.92, 0.95, 0.98));
  drawText(payload.saleDate, 420, height - 106, 10, false, rgb(0.92, 0.95, 0.98));

  drawText(`Customer: ${payload.customerName || "Walk-in customer"}`, 44, height - 150, 11, true);
  drawText(`Payment: ${payload.paymentMethod}`, 44, height - 168, 10);
  drawText(`Currency: ${payload.currencyCode}`, 420, height - 150, 10);

  const headerY = height - 210;
  page.drawRectangle({
    x: 36,
    y: headerY,
    width: 523,
    height: 28,
    color: rgb(0.95, 0.97, 0.98)
  });

  drawText("Medicine", 46, headerY + 10, 10, true);
  drawText("Batch", 256, headerY + 10, 10, true);
  drawText("Qty", 346, headerY + 10, 10, true);
  drawText("Price", 406, headerY + 10, 10, true);
  drawText("Amount", 486, headerY + 10, 10, true);

  let cursorY = headerY - 22;
  payload.items.forEach((item) => {
    drawText(item.medicine_name, 46, cursorY, 10, true);
    drawText(item.batch_number, 256, cursorY, 10);
    drawText(item.quantity.toFixed(2), 346, cursorY, 10);
    drawText(item.unit_price.toFixed(2), 406, cursorY, 10);
    drawText(item.line_total.toFixed(2), 486, cursorY, 10, true);
    cursorY -= 22;
  });

  cursorY -= 12;
  page.drawLine({
    start: { x: 330, y: cursorY },
    end: { x: 559, y: cursorY },
    color: rgb(0.85, 0.88, 0.9),
    thickness: 1
  });

  const totals = [
    ["Subtotal", payload.subtotal],
    ["Discount", payload.discountAmount],
    ["Tax", payload.taxAmount],
    ["Customer Due", payload.dueAmount],
    ["Collected", Math.max(payload.totalAmount - payload.dueAmount, 0)],
    ["Grand Total", payload.totalAmount]
  ] as const;

  cursorY -= 18;
  totals.forEach(([label, value], index) => {
    drawText(label, 388, cursorY, 10, index === totals.length - 1);
    drawText(value.toFixed(2), 492, cursorY, 10, true);
    cursorY -= 18;
  });

  if (payload.notes) {
    cursorY -= 12;
    drawText("Notes", 44, cursorY, 10, true);
    cursorY -= 16;
    drawText(payload.notes, 44, cursorY, 10);
  }

  drawText("Generated by THE SR'S PHARMACY", 44, 36, 10, true, rgb(0.2, 0.25, 0.32));
  drawText("Search-based billing. Barcode scanning disabled by design.", 44, 22, 9, false, rgb(0.35, 0.41, 0.48));

  return pdf.save();
}
